# Site settings

name: Kristel | Frontend Developer | UI/X Designer
email: kristelteng@gmail.com
title: Developer | UI/X Designer
description: >- # this means to ignore newlines until "baseurl:"
  A Graphic designer for 8 years, turned UX designer and software developer. Kristel loves merging the best of design and engineering. Bridging the gap between design and technical implementation, She works holistically considering both form and function.


url: "https://kristelteng.com" # the base hostname & protocol for your site

twitter_username: kristelthv
github_username:  kristelteng
linkedin_username: kristelteng

# Build settings
markdown: kramdown

baseurl: "" 

permalink: pretty

collections:
  works:
    output: true
    permalink: /work/:title
  wk-design: 
    output: true
    permalink: /work/design/:title
  wk-code: 
    output: true
    permalink: /work/code/:title
  wk-product: 
    output: true
    permalink: /work/product/:title
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

sass:
  sass_dir: _sass