# Site settings
name: Kristel
email: kristelteng@gmail.com
title: Developer | UI/X Designer

url: "https://kristelteng.com" # the base hostname & protocol for your site

twitter_username: kristelthv
github_username:  kristelteng
linkedin_username: kristelteng

# Build settings
markdown: kramdown

baseurl: "" # the subpath of your site, e.g. /blog

paginate: 5
paginate_path: "blog/page:num/"
gems: [jekyll-paginate]

permalink: pretty

collections:
  works:
    output: true
    permalink: /work/:title/
  recent:
    output: true
    permalink: /recent/:title/